Repository G-Research/fasttrackml, pull requests merged in 2023-12, with the labels that each got.

#672 Use the correct logger in NamespaceCachedRepository
  pkg/api/mlflow/dao/repositories/namespace_cached.go
Labels: bug

#675 Fix flaky Run flow integration test
  tests/integration/golang/mlflow/namespace/flows/run_test.go
Labels: tests

#659 Test NaN metrics values.
  pkg/api/mlflow/dao/convertors/log.go
  pkg/api/mlflow/dao/convertors/log_test.go
  pkg/api/mlflow/dao/convertors/metric.go
  pkg/api/mlflow/dao/convertors/metric_test.go
  pkg/api/mlflow/service/run/service.go
  tests/integration/golang/aim/metric/search_aligned_test.go
  tests/integration/golang/mlflow/run/log_batch_test.go
  tests/integration/golang/mlflow/run/log_metric_test.go
Labels: tests

#641 Adapt GetMetricHistory and GetMetricHistories to return context
  pkg/api/mlflow/api/response/metric.go
  pkg/api/mlflow/api/response/metric_test.go
  pkg/api/mlflow/controller/metric.go
  pkg/api/mlflow/dao/repositories/metric.go
  tests/integration/golang/fixtures/context.go
  tests/integration/golang/helpers/test.go
  tests/integration/golang/mlflow/metric/get_history_bulk_test.go
  tests/integration/golang/mlflow/metric/get_history_test.go
  tests/integration/golang/mlflow/namespace/flows/metric_test.go
Labels: enhancement, go

#687 Create a new server instance per test in the integration tests
  .github/workflows/ci.yml
  .vscode/launch.json
  Makefile
  tests/integration/docker-compose.yml
  tests/integration/golang/helpers/client.go
  tests/integration/golang/helpers/test.go
Labels: tests

#688 Hook up logging in integration tests
  Makefile
  tests/integration/docker-compose.yml
  tests/integration/golang/helpers/env.go
  tests/integration/golang/helpers/test.go
Labels: tests

#689 Parallelize integration tests
  .github/workflows/ci.yml
  Makefile
  tests/integration/docker-compose.yml
  tests/integration/golang/database/import_test.go
  tests/integration/golang/helpers/database.go
  tests/integration/golang/helpers/env.go
  tests/integration/golang/helpers/test.go
  tests/integration/golang/mlflow/namespace/flows/artifact_test.go
Labels: tests

#691 Revert the temporary solution of disabling cache for integration tests
  pkg/api/mlflow/dao/repositories/mock_namespace_repository_provider.go
  pkg/api/mlflow/dao/repositories/namespace.go
  pkg/api/mlflow/dao/repositories/namespace_cached.go
  pkg/common/middleware/namespace/namespace.go
  tests/integration/golang/helpers/client.go
Labels: tests

#695 Fix import from/to postgres
  pkg/database/import.go
  tests/integration/golang/database/import_test.go
Labels: bug

#697 Fix experiment name not being displayed in Aim UI run views
  pkg/api/aim/runs.go
  tests/integration/golang/aim/run/get_run_info_test.go
  tests/integration/golang/aim/run/get_runs_active_test.go
  tests/integration/golang/aim/run/search_test.go
  tests/integration/golang/fixtures/run.go
Labels: bug

#698 [release/0.4] Fix experiment name not being displayed in Aim UI run views
  pkg/api/aim/runs.go
  tests/integration/golang/aim/run/get_run_info_test.go
  tests/integration/golang/aim/run/get_runs_active_test.go
  tests/integration/golang/aim/run/search_test.go
  tests/integration/golang/fixtures/run.go
Labels: bug

#705 Group Dependabot AWS SDK pull requests
  .github/dependabot.yml
Labels: ci

#635 Adapt the Aim runs endpoints to return the context.
  pkg/api/aim/response/run.go
  pkg/api/aim/runs.go
  tests/integration/golang/aim/namespace/flows/run_test.go
  tests/integration/golang/aim/run/get_run_metrics_test.go
  tests/integration/golang/aim/run/get_runs_active_test.go
  tests/integration/golang/fixtures/context.go
  tests/integration/golang/fixtures/metric.go
  tests/integration/golang/fixtures/run.go
  tests/integration/golang/helpers/test.go
  tests/integration/golang/mlflow/metric/get_history_test.go
Labels: enhancement

#731 Improve the response types used for apps and dashboards in integration tests
  pkg/api/aim/response/app.go
  pkg/api/aim/response/dashboard.go
  tests/integration/golang/aim/app/get_apps_test.go
  tests/integration/golang/aim/dashboard/create_dashboard_test.go
  tests/integration/golang/aim/dashboard/get_dashboard_test.go
  tests/integration/golang/aim/dashboard/get_dashboards_test.go
  tests/integration/golang/aim/dashboard/update_dashboard_test.go
  tests/integration/golang/aim/namespace/flows/app_test.go
  tests/integration/golang/aim/namespace/flows/dashboard_test.go
Labels: tests

#732 Simplify app and dashboard creation in integration tests
  tests/integration/golang/aim/app/delete_app_test.go
  tests/integration/golang/aim/app/get_app_test.go
  tests/integration/golang/aim/app/update_app_test.go
  tests/integration/golang/aim/dashboard/create_dashboard_test.go
  tests/integration/golang/aim/dashboard/delete_dashboard_test.go
  tests/integration/golang/aim/dashboard/get_dashboard_test.go
  tests/integration/golang/aim/dashboard/get_dashboards_test.go
  tests/integration/golang/aim/dashboard/update_dashboard_test.go
  tests/integration/golang/database/import_test.go
  tests/integration/golang/fixtures/app.go
  tests/integration/golang/fixtures/dashboard.go
Labels: tests

#733 List most recent bookmarks on top
  pkg/api/aim/dashboards.go
  tests/integration/golang/aim/dashboard/get_dashboards_test.go
Labels: enhancement

#736 [release/0.4] Improve the response types used for apps and dashboards in integration tests
  pkg/api/aim/response/app.go
  pkg/api/aim/response/dashboard.go
  tests/integration/golang/aim/app/get_apps_test.go
  tests/integration/golang/aim/dashboard/create_dashboard_test.go
  tests/integration/golang/aim/dashboard/get_dashboard_test.go
  tests/integration/golang/aim/dashboard/get_dashboards_test.go
  tests/integration/golang/aim/dashboard/update_dashboard_test.go
  tests/integration/golang/aim/namespace/flows/app_test.go
  tests/integration/golang/aim/namespace/flows/dashboard_test.go
Labels: tests

#737 [release/0.4] Simplify app and dashboard creation in integration tests
  tests/integration/golang/aim/app/delete_app_test.go
  tests/integration/golang/aim/app/get_app_test.go
  tests/integration/golang/aim/app/update_app_test.go
  tests/integration/golang/aim/dashboard/create_dashboard_test.go
  tests/integration/golang/aim/dashboard/delete_dashboard_test.go
  tests/integration/golang/aim/dashboard/get_dashboard_test.go
  tests/integration/golang/aim/dashboard/get_dashboards_test.go
  tests/integration/golang/aim/dashboard/update_dashboard_test.go
  tests/integration/golang/database/import_test.go
  tests/integration/golang/fixtures/app.go
  tests/integration/golang/fixtures/dashboard.go
Labels: tests

#742 Make Aim UI local storage keys namespaced
  go.mod
  go.sum
Labels: bug

#743 [release/0.4] Make Aim UI local storage keys namespaced
  go.mod
  go.sum
Labels: bug

#619 Extend LogMetric and LogBatch to accept context
  pkg/api/mlflow/api/request/log.go
  pkg/api/mlflow/dao/convertors/log.go
  pkg/api/mlflow/dao/convertors/metric.go
  pkg/api/mlflow/dao/convertors/metric_test.go
  pkg/api/mlflow/dao/repositories/helpers.go
  pkg/api/mlflow/dao/repositories/metric.go
  tests/integration/golang/fixtures/context.go
  tests/integration/golang/fixtures/metric.go
  tests/integration/golang/helpers/test.go
  tests/integration/golang/mlflow/run/log_batch_test.go
  tests/integration/golang/mlflow/run/log_metric_test.go
Labels: enhancement, go

#763 Upgrade MLFlow integration tests to 2.9.2
  pkg/api/mlflow/config/config.go
  pkg/api/mlflow/config/config_test.go
  pkg/api/mlflow/dao/repositories/tag.go
  pkg/api/mlflow/service/artifact/service_test.go
  pkg/api/mlflow/service/artifact/validators.go
  pkg/api/mlflow/service/artifact/validators_test.go
  pkg/api/mlflow/service/run/service.go
  pkg/api/mlflow/service/run/service_test.go
  pkg/api/mlflow/service/run/validators.go
  pkg/api/mlflow/service/run/validators_test.go
  tests/integration/golang/mlflow/artifact/get_artifact_gs_test.go
  tests/integration/golang/mlflow/artifact/get_artifact_local_test.go
  tests/integration/golang/mlflow/artifact/get_artifact_s3_test.go
  tests/integration/golang/mlflow/artifact/list_gs_test.go
  tests/integration/golang/mlflow/artifact/list_local_test.go
  tests/integration/golang/mlflow/artifact/list_s3_test.go
  tests/integration/golang/mlflow/run/delete_tag_test.go
  tests/integration/golang/mlflow/run/set_tag_test.go
  tests/integration/python/config.json
  tests/integration/python/mlflow.patch
Labels: enhancement

#765 Bump actions/download-artifact and actions/upload-artifact from 3 to 4
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: ci

#744 Support for Context in LogMetric and LogBatch in Python API
  .gitignore
  Makefile
  docs/example/minimal_fasttrackml.py
  docs/fasttrackml_python_client.md
  python/fasttrackml/LICENSE
  python/fasttrackml/README.md
  python/fasttrackml/__init__.py
  python/fasttrackml/_tracking_service/client.py
  python/fasttrackml/client.py
  python/fasttrackml/entities/__init__.py
  python/fasttrackml/entities/metric.py
  python/fasttrackml/fluent.py
  python/fasttrackml/pyproject.toml
  python/fasttrackml/setup.py
  python/fasttrackml/store/custom_rest_store.py
Labels: enhancement, python

#766 Support for Context in GetMetricHistory and GetMetricHistories in Python API
  docs/example/minimal_fasttrackml.py
  docs/fasttrackml_python_client.md
  python/fasttrackml/_tracking_service/client.py
  python/fasttrackml/client.py
  python/fasttrackml/store/custom_rest_store.py
Labels: enhancement, python
