Repository G-Research/fasttrackml, pull requests merged in 2024-01, with the labels that each got.

#778 Prevent deletion of default namespace and default experiment
  pkg/api/admin/service/namespace/service.go
  pkg/api/admin/service/namespace/service_test.go
  pkg/api/aim/experiments.go
  pkg/api/mlflow/dao/models/experiment.go
  pkg/api/mlflow/dao/models/namespace.go
  pkg/api/mlflow/service/experiment/service.go
  pkg/api/mlflow/service/experiment/service_test.go
  pkg/common/middleware/namespace/namespace.go
  pkg/database/model.go
  pkg/ui/common/helpers.go
  pkg/ui/common/helpers_test.go
  tests/integration/golang/admin/namespace/delete_test.go
  tests/integration/golang/admin/namespace/update_test.go
  tests/integration/golang/aim/experiment/delete_test.go
  tests/integration/golang/mlflow/experiment/delete_test.go
Labels: enhancement

#796 Create GetCurrentNamespace and ListNamespace endpoints
  pkg/api/admin/api/response/namespace.go
  pkg/api/admin/controller/controller.go
  pkg/api/admin/controller/namespace.go
  pkg/api/admin/routes.go
  pkg/server/server.go
  tests/integration/golang/admin/namespace/get_current_test.go
  tests/integration/golang/admin/namespace/list_test.go
  tests/integration/golang/fixtures/namespace.go
Labels: enhancement, go

#807 Bump github.com/apache/arrow from 12.0.1 to 14.0.2
  go.mod
  go.sum
  pkg/api/mlflow/controller/helpers.go
  pkg/api/mlflow/controller/metric.go
  tests/integration/golang/helpers/arrow.go
Labels: go

#821 Bump go-sqlite3 library to SQLite3MultipleCiphers 1.8.2 / SQLite3 3.45.0
  go.mod
  go.sum
  pkg/api/aim/query/clause.go
  pkg/api/aim/query/query_test.go
  pkg/api/mlflow/dao/repositories/helpers.go
  pkg/api/mlflow/dao/repositories/helpers_test.go
Labels: enhancement
